// Source - http://www.djtech.net/humor/useless_facts.htm
// Source - http://laughbreak.com/lists/useless-facts/
// Source - http://laughbreak.com/lists/useless-facts-2/

var useless_facts = new Array("A maioria das buzinas dos carros americanos toca na tonalidade F.",
    "O nome Wendy foi inventado para o livro 'Peter Pan'",
    "O nome completo da Barbie é Barbara Millicent Roberts.",
    "Cada vez que você lambe um selo, você consome 1/10 de uma caloria.",
    "Uma pessoa normal adormece em sete minutos.",
    "Estudos mostram que se um gato cair do sétimo andar de um prédio, ele tem cerca de trinta por cento menos chance de sobreviver do que um gato que cai do vigésimo andar. Supõe-se que leva cerca de oito andares para o gato perceber o que está acontecendo, relaxe e corrigir-se.",
    "Seu estômago tem que produzir uma nova camada de muco a cada 2 semanas, senão ele vai digerir sozinho.",
    "O refrigerante cítrico 7-UP foi criado em 1929; '7' foi selecionado após os recipientes originais de 7 onças e 'UP' para a direção das bolhas.",
    "101 Dálmatas, Peter Pan, A Dama e o Vagabundo e Mulan são os únicos desenhos animados da Disney em que ambos os pais estão presentes e não morrem ao longo do filme.",
    "O orgasmo de um porco dura 30 minutos.",
    "'Aeromoças' é a palavra mais longa digitada apenas com a mão esquerda.",
    "Para escapar das garras de um crocodilo, empurre seus polegares em seus globos oculares - ele o deixará ir instantaneamente.",
    "As renas gostam de comer bananas.",
    "Nenhuma palavra na língua inglesa rima com mês, laranja, prata e roxo.",
    "A palavra 'samba' significa 'esfregar umbigos juntos'",
    "Mel Blanc (a voz do Pernalonga) era alérgico a cenoura.",
    "A cadeira elétrica foi inventada por um dentista.",
    "A primeira bomba lançada pelos Aliados em Berlim durante a Segunda Guerra Mundial matou o único elefante no Zoológico de Berlim.",
    "Mais pessoas são mortas anualmente por burros do que acidentes de avião.",
    "Um 'instante' é uma unidade de tempo para 1/100 de segundo.", "O pênis de uma baleia é chamado de idiota.",
    "Devido à rotação da Terra, um objeto pode ser lançado mais longe se for lançado para o oeste.",
    "A pessoa média passa 6 meses de sua vida parada em sinais vermelhos.",
    "Em 1912, uma lei foi aprovada em Nebraska, exigindo que os motoristas do país à noite parassem a cada 150 metros, disparassem um foguete, esperassem oito minutos para a estrada ficar livre antes de prosseguir com cautela, o tempo todo buzinando e disparando sinalizadores. .",
    "Mais dinheiro do monopólio é impresso em um ano do que dinheiro real em todo o mundo.",
    "A salada Caesar não tem nada a ver com nenhum dos Caesars. Foi preparada pela primeira vez em um bar em Tijuana, no México, na década de 1920.",
    "Um quarto dos ossos do seu corpo estão nos pés.",
    "Crocodilos e jacarés são surpreendentemente rápidos em terra. Embora sejam rápidos, não são ágeis. Portanto, se estiver sendo perseguido por um deles, corra em zigue-zague para despistá-lo.",
    "A Fremont Bridge de Seattle sobe e desce mais do que qualquer ponte levadiça do mundo.",
    "As pessoas destras vivem, em média; nove anos a mais do que as canhotas.",
    "Dez por cento da receita do governo russo vem da venda de vodca.",
    "Nos Estados Unidos, um quilo de batatas fritas custa duzentas vezes mais do que um quilo de batatas.",
    "Uma girafa pode ficar sem água por mais tempo do que um camelo.",
    "Uma pessoa não consegue saborear a comida a menos que esteja misturada com saliva. Por exemplo, se uma substância de sabor forte, como sal, for colocada em uma língua seca, as papilas gustativas não serão capazes de prová-la. Assim que uma gota de saliva for adicionado e o sal é dissolvido, no entanto, resulta uma sensação de sabor definida. Isso é verdade para todos os alimentos.",
    "Quase 80% de todos os animais da Terra têm seis patas.",
    "Na cerimônia de casamento dos antigos índios incas do Peru, o casal era considerado oficialmente casado quando tiravam as sandálias e as entregavam um ao outro.",
    "Noventa por cento de todas as espécies extintas são aves.",
    "Existe aproximadamente uma galinha para cada ser humano no mundo.",
    "A maioria das ligações a cobrar é feita no dia dos pais.",
    "A primeira corrida automobilística já vista nos Estados Unidos foi realizada em Chicago em 1895. A pista ia de Chicago a Evanston, Illinois. O vencedor foi J. Frank Duryea, cuja velocidade média era de 71/2 milhas por hora.",
    "Cada um de nós gera cerca de 3,5 quilos de lixo por dia, a maior parte papel.",
    "As mulheres administram o dinheiro e pagam as contas em 75% dos lares americanos.",
    "Um arco-íris pode ser visto apenas pela manhã ou no final da tarde. Ele pode ocorrer apenas quando o sol está 40 graus ou menos acima do horizonte.",
    "NUNCA choveu em Calama, uma cidade no deserto de Atacama no Chile.",
    "Custa mais comprar um carro novo hoje nos Estados Unidos do que custou a Cristóvão Colombo equipar e realizar três viagens de e para o Novo Mundo.",
    "As coisas de plástico na ponta dos cadarços são chamadas de aglets.",
    "Um alemão do século XVIII chamado Matthew Birchinger, conhecido como 'o homenzinho de Nuremberg', tocava quatro instrumentos musicais, incluindo a gaita de fole, era um calígrafo experiente e o mágico de palco mais famoso de sua época. Ele fazia truques com o copo e bolas que nunca foram explicadas. No entanto, Birchinger não tinha mãos, pernas ou coxas e tinha menos de 29 polegadas de altura.",
    "O horário de verão não é observado na maior parte do estado do Arizona e partes de Indiana.",
    "As formigas se assemelham muito às maneiras humanas: quando acordam, elas se espreguiçam e parecem bocejar de maneira humana antes de assumir as tarefas do dia.",
    "As abelhas têm 5 olhos. Existem 3 olhos pequenos no topo da cabeça de uma abelha e 2 maiores na frente.",
    "Conte o número de cricket cricket em um período de 15 segundos, adicione 37 ao total e seu resultado será muito próximo da temperatura real externa em Fahrenheit.",
    "Um quarto da população mundial vive com menos de US$ 200 por ano. Noventa milhões de pessoas sobrevivem com menos de US$ 75 por ano.",
    "As borboletas provam com as patas traseiras.",
    "Apenas picada de mosquito fêmea e a maioria é atraída pela cor azul duas vezes mais do que por qualquer outra cor.",
    "Se alguém colocar uma pequena quantidade de bebida em um escorpião, ele enlouquecerá instantaneamente e se picará até a morte.",
    "É ilegal caçar camelos no estado do Arizona.",
    "Nos antros de jogo ingleses do século XVIII, havia um funcionário cujo único trabalho era engolir os dados se houvesse uma batida policial.",
    "Não há relógios nos cassinos de Las Vegas.",
    "A língua humana prova coisas amargas com as papilas gustativas voltadas para trás. Sabores salgados e picantes são provados no meio da língua, sabores doces na ponta!",
    "O primeiro produto a ter código de barras foi o chiclete Wrigley.",
    "Ao espirrar, o ar e as partículas passam pelas narinas a uma velocidade superior a 160 km/h. Nesse período, todas as funções corporais param, inclusive o coração, o que contribui para a impossibilidade de manter os olhos abertos durante o espirro.",
    "O crescimento anual do tráfego WWW é de 314.000%",
    "%60 de todas as pessoas que usam a Internet, usam-na para pornografia.",
    "Em 1778, as mulheres elegantes de Paris nunca saíam em tempo tempestuoso sem um para-raios preso ao chapéu.",
    "O sexo queima 360 calorias por hora.",
    "Uma uva-passa jogada em uma taça de champanhe fresca vai saltar para cima e para baixo continuamente do fundo da taça para o topo.",
    "O aipo tem calorias negativas! São necessárias mais calorias para comer um pedaço de aipo do que o aipo contém.",
    "O lápis de grafite médio traçará uma linha de 35 milhas de comprimento ou escreverá aproximadamente 50.000 palavras em inglês. Mais de 2 bilhões de lápis são fabricados a cada ano nos Estados Unidos. Se eles fossem colocados de ponta a ponta, dariam a volta ao mundo nove vezes.",
    "O estalo que você ouve quando estala os dedos é na verdade uma bolha de gás queimando.",
    "Uma tradução literal de um sinal de trânsito padrão na China: 'Dê grande espaço para o cão festivo que faz esporte na estrada.'",
    "Você queima mais calorias dormindo do que assistindo TV.",
    "Larry Lewis correu a corrida de 100 jardas em 17,8 segundos em 1969, estabelecendo assim um novo recorde mundial para corredores na classe de 100 anos ou mais. Ele tinha 101.",
    "Durante a vida, o ser humano médio produz litros de cuspe suficientes para encher 2 piscinas.",
    "É contra a lei cochilar sob um secador de cabelo na Flórida/contra a lei dar um tapa nas costas de um velho amigo na Geórgia/contra a lei jogar amarelinha em um domingo no Missouri.",
    "As medidas da Barbie, se ela fosse em tamanho real, seriam 39-29-33.",
    "O coração humano cria pressão suficiente para esguichar sangue a 30 pés.",
    "Um terço de todos os cânceres estão relacionados ao sol.",
    "A BOLA DE CANHÃO MAIS INCOMUM: Em duas ocasiões, a senhorita 'Rita Thunderbird' permaneceu dentro do canhão, apesar de muitos incentivos da pólvora para fazer o contrário. Ela se apresentou com um biquíni de lamê dourado e em uma das duas ocasiões (1977) a senhorita Thunderbird permaneceu alojada no canhão, enquanto seu sutiã foi baleado no rio Tâmisa.",
    "Estima-se que os humanos usam apenas 10% do cérebro.",
    "Valentine Tapley, do condado de Pike, Missouri, cresceu bigodes atingindo um comprimento de doze pés e seis polegadas de 1860 até sua morte em 1910, protestando contra a eleição de Abraham Lincoln para a presidência.",
    "A maioria dos egípcios morreu aos 30 anos, cerca de 300 anos atrás",
    "Por algum tempo Frederic Chopin, o compositor e pianista, usava barba apenas de um lado do rosto, explicando: 'Não importa, meu público vê apenas meu lado direito.'",
    "1 em cada 4 americanos apareceu de uma forma ou de outra na televisão.",
    "1 em cada 8 americanos já trabalhou em um restaurante McDonalds.",
    "70% de todos os barcos vendidos são usados ​​para pesca.",
    "Estudos mostraram que crianças riem em média 300 vezes/dia e adultos 17 vezes/dia, tornando a criança média mais otimista, curiosa e criativa do que o adulto.",
    "Um peixinho dourado grávido é chamado de twit.",
    "A guerra mais curta da história foi entre Zanzibar e a Inglaterra em 1896. Zanzibar se rendeu após 38 minutos.",
    "Você nasceu com 300 ossos, mas quando for adulto terá apenas 206.",
    "Se você ficar cego de um olho, perderá apenas cerca de um quinto de sua visão, mas todo o seu senso de profundidade.",
    "As mulheres piscam quase duas vezes mais que os homens.",
    "O músculo mais forte (em relação ao tamanho) do corpo é a língua.",
    "A envergadura de um Boeing 747 é maior do que o primeiro voo do irmão Wright.",
    "A American Airlines economizou US$ 40.000 em 1987 eliminando uma azeitona de cada salada servida na primeira classe.",
    "Tempo de vida médio de uma liga principal de beisebol: 7 arremessos.",
    "Um palíndromo é uma sentença ou grupo de sentenças cuja leitura é a mesma de trás para frente e de trás para frente: Ex: 'Rum vermelho, senhor, é assassinato.' 'Mamãe é tão altruísta quanto eu.' 'Enfermeira, eu espio ciganos. Corra!''Um homem, um plano, um canal - Panamá.' 'Ele viveu como um demônio, hein?'",
    "O primeiro CD impresso nos EUA foi 'Born in the USA' de Bruce Springsteen",
    "Em 1986, o Congresso e o presidente Ronald Reagan assinaram a Lei Pública 99-359, que mudou o horário de verão do último domingo de abril para o primeiro domingo de abril. do mês de abril a D.S.T.",
    "A unha do polegar cresce mais devagar, a unha do meio mais rápido, quase 4 vezes mais rápido que as unhas dos pés.",
    "Os olhos humanos nunca crescem, mas o nariz e as orelhas nunca param de crescer.",
    "Os 57 frascos de ketchup da Heinz representam o número de variedades de picles que a empresa já teve.",
    "Tom Sawyer foi o primeiro romance escrito em uma máquina de escrever.",
    "Se o Texas fosse um país, seu PIB seria o quinto maior de qualquer país do mundo.",
    "Há 1 milhão de formigas para cada ser humano no mundo.",
    "Probabilidades de ser morto por um raio? 1 em 2 milhões/morto em um acidente de carro? 1 em 5.000/morto por cair da cama? 1 em 2 milhões/morto em um acidente de avião? 1 em 25 milhões.",
    "Desde 1978, 37 pessoas morreram devido à queda de máquinas de venda automática. 13 pessoas são mortas anualmente. Tudo isso enquanto tentavam tirar mercadorias delas. 113 pessoas ficaram feridas.",
    "Metade dos alimentos consumidos hoje em todo o mundo foram desenvolvidos por agricultores da Cordilheira dos Andes (incluindo batata, milho, batata-doce, abóbora, todas as variedades de feijão, amendoim, mandioca, mamão, morango, amora e muitos outros).",
    "Os 'Arcos Dourados' da rede de fast food McDonalds são mais reconhecidos mundialmente do que a cruz religiosa do cristianismo.",
    "O ex-astro do basquete Michael Jordan é o rosto mais reconhecido do mundo, mais do que o próprio papa.",
    "O falante médio borrifa cerca de 300 gotículas microscópicas de saliva por minuto, cerca de 2,5 gotículas por palavra.",
    "A Terra experimenta 50.000 terremotos por ano e é atingida por raios 100 vezes por segundo.",
    "Todos os anos, 11.000 americanos se machucam enquanto tentam posições sexuais bizarras.",
    "Se tivéssemos a mesma taxa de mortalidade agora que em 1900, mais da metade das pessoas no mundo hoje não estariam vivas.",
    "Em média, os americanos comem 18 acres de pizza todos os dias.",
    "Pesquisadores do Departamento de Rodovias do Texas em Fort Worth determinaram que a população de vacas dos EUA arrota cerca de 50 milhões de toneladas de hidrocarbonetos valiosos na atmosfera a cada ano. Os arrotos acumulados de dez vacas médias podem manter uma pequena casa adequadamente aquecida e seu fogão funcionando por um ano.",
    "Durante uma forte tempestade de vento ou chuva, o Empire State Building balança vários metros para os lados.",
    "Nos últimos 3.500 anos, houve aproximadamente 230 anos de paz em todo o mundo civilizado.",
    "A Peste Negra reduziu a população da Europa em um terço no período de 1347 a 1351.",
    "A pessoa média passa cerca de dois anos ao telefone na vida.",
    "Comprimento de barba que um homem médio deixaria crescer se nunca raspasse 27,5 pés",
    "Mais de 60% de todos os que se casam se divorciam.", "400 quartos de libra podem ser feitos de 1 vaca.",
    "Um superpetroleiro totalmente carregado viajando em velocidade normal leva pelo menos 20 minutos para parar.",
    "A Coca-Cola era originalmente verde.", "Os homens podem ler letras menores do que as mulheres; as mulheres podem ouvir melhor.",
    "Hong Kong detém o maior número de Rolls Royce's per capita.",
    "Número médio de dias que um alemão ocidental fica sem lavar a cueca: 7",
    "Pilotos de caça da Segunda Guerra Mundial no Pacífico Sul armaram seus aviões enquanto estacionados com cintos de munição de metralhadora calibre . ', daí o termo.",
    "Número médio de pessoas no ar sobre os EUA a qualquer hora: 61.000.",
    "Pessoas inteligentes têm mais zinco e cobre no cabelo.",
    "A Islândia consome mais Coca-Cola per capita do que qualquer outra nação.",
    "No início da década de 1940, a FCC atribuiu o Canal 1 da televisão a serviços móveis (como rádios bidirecionais em táxis), mas não renumera as atribuições de outros canais.",
    "Os teleféricos de São Francisco são os únicos monumentos nacionais móveis.",
    "Os quartéis de bombeiros têm escadas circulares originárias dos velhos tempos, quando as locomotivas eram puxadas por cavalos. Os cavalos eram estabulados no andar térreo e aprenderam a subir escadas retas.",
    "A Biblioteca Principal da Universidade de Indiana afunda mais de uma polegada a cada ano porque, quando foi construída, os engenheiros não levaram em conta o peso de todos os livros que ocupariam o prédio.",
    "111.111.111 x 111.111.111 = 12.345.678.987.654.321",
    "Estátuas em parques: Se o cavalo tiver as duas patas dianteiras no ar, a pessoa morreu em batalha; se o cavalo tiver uma perna dianteira no ar, a pessoa morreu em consequência dos ferimentos recebidos na batalha; se o cavalo tiver todas quatro patas no chão, a pessoa morreu de causas naturais.",
    "A expressão 'ser demitido' vem de clãs antigos que queriam se livrar de pessoas indesejadas, então eles queimavam suas casas em vez de matá-los, criando o termo 'foi demitido'.",
    "'Eu sou.' é a frase completa mais curta da língua inglesa.",
    "Hershey's Kisses são chamados assim porque a máquina que os fabrica parece estar beijando a esteira.",
    "A expressão 'regra de ouro' é derivada de uma antiga lei inglesa, que afirmava que você não poderia bater em sua esposa com nada mais largo do que o polegar.",
    "O vôo mais longo registrado de uma galinha é de treze segundos.",
    "O sistema interestadual de Eisenhower exige que uma milha em cada cinco seja reta em caso de guerra ou emergência, elas podem ser usadas como pistas de pouso.",
    "O nome Jeep veio da abreviação usada no exército. G.P. para 'veículo de uso geral'.",
    "O Pentágono, em Arlington, Virgínia, tem o dobro de banheiros do necessário, porque quando foi construído na década de 1940, o estado da Virgínia ainda tinha leis de segregação que exigiam banheiros separados para negros e brancos.",
    "O navio de cruzeiro, Queen Elizabeth II, move-se apenas 15 centímetros para cada galão de diesel que queima.",
    "Se você tem três quartos, quatro centavos e quatro centavos, você tem $ 1,19, a maior quantia de dinheiro em moedas sem poder trocá-lo por um dólar.",
    "Em Aspen Colorado, você pode ter uma renda máxima de $ 104.000 e ainda receber habitação subsidiada pelo governo.",
    "Buscar buzinas para um casal que acabou de se casar é uma velha superstição para garantir um ótimo sexo.",
    "Dr. Kellogg introduziu Corn Flakes da Kellogg's na esperança de que reduzisse a masturbação.",
    "O esperma de um camundongo é, na verdade, mais longo que o de um elefante.",
    "Na França medieval, esposas infiéis eram obrigadas a perseguir uma galinha nua pela cidade.",
    "A aranha Viúva Negra come seu companheiro durante ou após o sexo.",
    "O pênis de Napoleão foi vendido a um urologista americano por US$ 40.000.",
    "Comer o coração de uma perdiz masculina era a cura para a impotência na antiga Babilônia.",
    "Um touro pode inseminar 300 vacas com uma única ejaculação.",
    "Quando uma havaiana usa uma flor sobre a orelha esquerda, significa que ela não está disponível.",
    "O ícone 'salvar' no Microsoft Word mostra um disquete com o obturador ao contrário.",
    "A única nação cujo nome começa com 'A', mas não termina com 'A' é o Afeganistão.",
    "A seguinte frase: 'Um lavrador pensativo, de casaco áspero e rosto macilento, caminhou pelas ruas de Scarborough; depois de cair em um pântano, ele tossiu e soluçou.' Contém as nove pronúncias diferentes de 'ough' no idioma inglês.",
    "O verbo 'cleave' é a única palavra em inglês com dois sinônimos que são antônimos um do outro: aderir e separar.",
    "A única palavra de 15 letras que pode ser soletrada sem repetir uma letra não é protegida por direitos autorais.",
    "A forma das células do colênquima vegetal e a forma das bolhas na espuma da cerveja são as mesmas - são ortotetraquidecaedros.",
    "Emus e cangurus não podem andar para trás e estão no brasão australiano por esse motivo.",
    "Os gatos têm mais de cem sons vocais, enquanto os cães têm apenas cerca de dez.",
    "Blueberry Jelly Barrigas foram criadas especialmente para Ronald Reagan.",
    "O doce PEZ ainda vem no sabor Café.",
    "A primeira música tocada na Rádio das Forças Armadas durante a operação Desert Shield foi 'Rock the Casba' do Clash.",
    "Creme não lácteo é inflamável.",
    "O avião em que Buddy Holly morreu era o 'American Pie'. (Daí o nome da música de Don McLean.)",
    "Cada rei em um baralho de cartas representa um grande rei da história. Espadas - Rei Davi, Paus - Alexandre, o Grande, Copas - Carlos Magno e Ouros - Júlio César.",
    "Os campos de golfe cobrem 4% da América do Norte.",
    "A pessoa média comerá acidentalmente pouco menos de um quilo de insetos a cada ano.",
    "Até 1994, mapas-múndi e globos vendidos na Albânia continham apenas a Albânia.",
    "O valor de Pi será oficialmente 'arredondado para baixo' para 3,14 de 3,14159265359 em 31 de dezembro de 1999.",
    "A Grande Muralha da China é a única estrutura feita pelo homem visível do espaço.",
    "Um pedaço de papel não pode ser dobrado mais de 9 vezes.",
    "A quantidade de memória do computador necessária para executar o WordPerfect for Win95 é 8 vezes a quantidade necessária a bordo do ônibus espacial.",
    "O norte-americano médio comerá 35.000 biscoitos durante sua vida.",
    "Entre 25% e 33% da população espirra quando exposta à luz.",
    "O nome mais comum no mundo é Mohammed.",
    "O Monte Olimpo Mons em Marte é três vezes o tamanho do Monte Everest.",
    "A maioria dos banheiros dá descarga no apartamento E.",
    "2.000 libras de poeira espacial e outros detritos espaciais caem na Terra todos os dias.",
    "A cada mês, há pelo menos um relato de OVNIs de cada província do Canadá.",
    "40.000 americanos são feridos por banheiros a cada ano.",
    "Você pode ser multado em até US$ 1.000 por assobiar no domingo em Salt Lake City, Utah.",
    "Demora cerca de 142,18 licks para chegar ao centro de um pop Tootsie.",
    "O número de série do primeiro MAC já produzido foi 2001.",
    "É ilegal comer laranjas durante o banho na Califórnia.",
    "Se feito perfeitamente, uma combinação de cubo rubix pode ser resolvida em 17 voltas.",
    "A bunda americana média tem 14,9 polegadas de comprimento.",
    "Mais balas foram disparadas em 'Starship Troopers' do que qualquer outro filme já feito.",
    "60% das eletrocussões ocorrem ao falar ao telefone durante uma tempestade.",
    "O nome da menina na estátua da liberdade é Mãe dos Exilados.",
    "3,6 latas de Spam são consumidas a cada segundo.",
    "Há uma pausa sistemática na conversa a cada 7 minutos.",
    "O zumbido de um barbeador elétrico na América toca no tom de si bemol; tom de sol na Inglaterra.",
    "São 1.575 degraus do andar térreo até o topo do edifício Empire State.",
    "O recorde mundial para manter um salva-vidas na boca com o buraco intacto é de 7 horas e 10 minutos.",
    "Existem 293 maneiras de fazer troco por um dólar.",
    "O recorde mundial para cuspir uma semente de melancia é de 65 pés e 4 polegadas.",
    "Na selva filipina, o ioiô foi usado pela primeira vez como arma.",
    "O duelo é legal no Paraguai desde que ambas as partes sejam doadoras de sangue registradas.",
    "Texas também é o único estado que tem permissão para hastear sua bandeira estadual na mesma altura que a bandeira dos EUA.",
    "Os três nomes ocidentais mais reconhecidos na China são Jesus Cristo, Richard Nixon e Elvis Presley.",
    "Há uma cidade em Newfoundland, Canadá, chamada Dildo.",
    "A Boston University Bridge (na Commonwealth Avenue, Boston, Massachusetts) é o único lugar no mundo onde um barco pode navegar sob um trem passando por baixo de um carro passando por baixo de um avião.",
    "Todos os 50 estados estão listados na parte superior do Lincoln Memorial no verso da nota de US$ 5.",
    "No espaço, os astronautas não conseguem chorar, porque não há gravidade e as lágrimas não vão rolar.",
    "Mascar chiclete enquanto descasca cebola evita que você chore.",
    "Existem mais flamingos de plástico nos Estados Unidos do que reais.",
    "O estalo de um chicote é na verdade um pequeno estrondo sônico, já que a ponta quebra a barreira do som.",
    "Júpiter é maior do que todos os outros planetas do nosso sistema solar juntos.",
    "Água quente é mais pesada que fria.",
    "A ideia comum de que apenas 10% do cérebro é usado não é verdade, pois é impossível determinar a porcentagem real devido à complexidade do cérebro.",
    "Os dardos são ilegais no Canadá.",
    "Há mais psicanalistas per capita em Buenos Aires do que em qualquer outro lugar do mundo.",
    "Entre 2 e 3 jóqueis são mortos a cada ano em corridas de cavalos.",
    "5.840 pessoas com ferimentos relacionados a travesseiros deram entrada em salas de emergência dos Estados Unidos em 1992.",
    "A mulher média consome 3 quilos de batom durante a vida.",
    "Algumas pessoas expressam preocupação em compartilhar seu sabonete, e com razão, considerando que 75% de todas as pessoas lavam de cima para baixo.",
    "A concepção ocorre mais no mês de dezembro.",
    "'60 Minutes' da CBS é o único programa de TV sem uma música/música tema.",
    "Metade de todos os americanos vivem a menos de 80 quilômetros de seu local de nascimento.",
    "'Obsession' é o nome de barco mais popular.", "Em média, o cheiro favorito dos americanos é banana.",
    "Se alguém soletrar números, eles teriam que contar até mil antes de encontrar a letra 'A'.",
    "O mel é o único alimento que não estraga.", "3,9% das mulheres não usam calcinha.",
    "Esta ocorrência cotidiana comum composta de 59% de nitrogênio, 21% de hidrogênio e 9% de dióxido é chamada de 'peido'.",
    "'Avaliação e Parametrização das Características de Desempenho de Estabilidade e Segurança de Brinquedos Veiculares de Duas e Três Rodas para Passeio.' Título de um projeto de pesquisa de $ 230.000 proposto pelo Departamento de Saúde, Educação e Bem-Estar, para estudar as várias maneiras pelas quais as crianças caem de bicicletas.",
    "Os bebês nascem sem patelas. Eles não aparecem até que a criança atinja 2-6 anos de idade.",
    "Os meteorologistas afirmam que estão certos 85% das vezes (pense nisso!)",
    "Em 1980, um hospital de Las Vegas suspendeu funcionários por apostarem em quando os pacientes morreriam.",
    "O nome completo de Los Angeles 'El Pueblo de Nuestra Senora la Reina de Los Angeles de Porciuncula' é reduzido para 3,63% de seu tamanho na abreviatura 'L.A.'.",
    "Se você fosse para o espaço, explodiria antes de sufocar porque não há pressão de ar.",
    "A única pessoa real que apareceu em um dispensador de pez foi Betsy Ross.",
    "A mãe de Mike Nesmith (o guitarrista dos Monkeys) inventou o White Out.",
    "Apenas 6 pessoas em todo o mundo morreram de mosh.",
    "241. Em um teste realizado por cientistas canadenses, usando vários estilos diferentes de música, foi determinado que as galinhas põem mais ovos quando a música pop é tocada.",
    "A capacidade de armazenamento do cérebro humano excede 4 Terabytes.",
    "Em Vermont, a proporção de vacas para pessoas é de 10:1",
    "Qualquer líquido em movimento livre no espaço sideral se transformará em uma esfera, por causa de sua tensão superficial.",
    "O americano médio olha para oito casas antes de comprar uma.",
    "Na vida média, uma pessoa andará o equivalente a 5 vezes ao redor do equador.",
    "Koala é a palavra aborígine para 'não beber'.", "Shakespeare soletrou seu PRÓPRIO nome de várias maneiras diferentes.",
    "O primeiro anticoncepcional foi o esterco de crocodilo usado pelos antigos egípcios.",
    "Uma assinatura é chamada de John Hancock porque ele assinou a Declaração de Independência. Apenas 2 pessoas assinaram a declaração de independência em 4 de julho. A última pessoa assinou 2 anos depois.",
    "Arnold Schonberg sofria de triscaidecafobia, o medo do número 13. Ele morreu aos 13 minutos da meia-noite de sexta-feira 13.",
    "Mozart escreveu a canção de ninar 'twinkle, twinkle, little star' aos 5 anos de idade.",
    "O meteorologista Willard Scott foi o primeiro Ronald McDonald original.",
    "Virginia Woolf escreveu todos os seus livros de pé.",
    "Einstein não conseguia falar fluentemente até depois de seu nono aniversário. Seus pais achavam que ele era retardado mental.",
    "O cartão de visita de Al Capone dizia que ele era um comerciante de móveis usados.",
    "Deborah Winger fez a voz de E.T.",
    "Kelsey Grammar canta e toca piano para a música tema de Fraiser.",
    "Thomas Edison, aclamado inventor da lâmpada, tinha medo do escuro.",
    "Na Inglaterra, o presidente da Câmara não tem permissão para falar.",
    "Você pode navegar ao redor do mundo na latitude 60 graus sul.",
    "A terra pesa cerca de 6.588.000.000.000.000.000.000.000.000 de toneladas.",
    "Amendoins são um dos ingredientes da dinamite.", "Porcos-espinhos podem flutuar na água.",
    "A mão esquerda de uma pessoa comum faz 56% da digitação.",
    "Um tubarão é o único peixe que pode piscar com os dois olhos.",
    "A palavra de uma sílaba mais longa na língua inglesa é 'screeched.'",
    "Todos os relógios do filme 'Pulp Fiction' estão parados em 4:20, uma hora nacional para fumantes de maconha.",
    "'Dreamt' é a única palavra em inglês que termina com as letras 'mt.'",
    "As amêndoas são um membro da família do pêssego.",
    "Winston Churchill nasceu em um banheiro feminino durante uma dança.",
    "Maine é o único estado cujo nome tem apenas uma sílaba.",
    "Existem apenas quatro palavras na língua inglesa que terminam em 'dous': tremendo, horrendo, estupendo e perigoso.",
    "Tigres não só têm pêlo listrado, como também pele listrada!",
    "Na maioria dos anúncios, incluindo jornais, a hora exibida em um relógio é 10:10.",
    "No chão, um bando de gansos é um bando, no céu é uma meada.",
    "Para Garantir a Prontidão, espera-se que se pague além do valor do serviço – daí a sigla posterior: T.I.P.",
    "Quando os Cornhuskers da Universidade de Nebraska jogam futebol em casa, o estádio se torna a terceira maior cidade do estado.",
    "Os personagens Bert e Ernie na Vila Sésamo receberam o nome de Bert, o policial, e Ernie, o motorista de táxi em 'Its A Wonderful Life', de Frank Capra.",
    "Uma libélula tem uma vida útil de 24 horas.",
    "Uma moeda de dez centavos tem 118 arestas ao redor da borda.",
    "Em uma nota de um dólar americano, há uma coruja no canto superior esquerdo do '1' envolto no 'escudo' e uma aranha escondida no canto superior direito frontal.",
    "O nome de Oz no 'Mágico de Oz' foi inventado quando o criador, Frank Baum, olhou para seu arquivo e viu A-N e O-Z; daí o nome 'OZ.'",
    "O micro-ondas foi inventado depois que um pesquisador passou por um tubo de radar e uma barra de chocolate derreteu em seu bolso.",
    "O Sr. Rogers é um ministro ordenado.", "A primeira namorada de John Lennon chamava-se Thelma Pickles.",
    "Existem 336 ondulações em uma bola de golfe normal.",
    "A cena em que Indiana Jones atira no espadachim em Raider's of the Lost Ark foi ideia de Harrison Ford para que ele pudesse ir ao banheiro.",
    "Um crocodilo não pode colocar a língua para fora.", "Um caracol pode dormir por três anos.",
    "Todos os ursos polares são canhotos.", "A China tem mais falantes de inglês do que os Estados Unidos.",
    "Elefantes são os únicos animais que não podem pular.",
    "Fevereiro de 1865 é o único mês registrado na história a não ter lua cheia.",
    "Se a população da China passasse por você em fila única, a fila nunca terminaria por causa da taxa de reprodução.",
    "Se você gritou por 8 anos, 7 meses e 6 dias, terá produzido energia sonora suficiente para esquentar uma xícara de café.",
    "Nos últimos 4000 anos, nenhum novo animal foi domesticado.",
    "Leonardo Da Vinci inventou a tesoura.",
    "A palavra 'conjunto' tem mais definições do que qualquer outra palavra na língua inglesa.",
    "A noz-moscada é extremamente venenosa se injetada por via intravenosa.",
    "Em média, as pessoas temem mais as aranhas do que a morte.",
    "Uma das razões pelas quais a maconha é ilegal hoje é porque os produtores de algodão na década de 1930 faziam lobby contra os agricultores de cânhamo, eles viam isso como uma competição.",
    "Shakespeare inventou a palavra 'assassinato' e 'bater'.", "Alguns leões acasalam mais de 50 vezes por dia.",
    "Estrela do mar não tem cérebro.", "A formiga sempre cai para o lado direito quando embriagada.",
    "O nome de todos os continentes do mundo termina com a mesma letra que começa.",
    "Existem dois cartões de crédito para cada pessoa nos Estados Unidos.",
    "A palavra mais longa composta por uma linha no teclado é: TYPEWRITER",
    "Você não pode se matar prendendo a respiração.",
    "A pessoa média passa 12 semanas por ano 'procurando coisas'.",
    "O símbolo na tecla 'libra' (#) é chamado de octothorpe.. ",
    "O ponto sobre a letra 'i' é chamado de til.", "Unhas encravadas são hereditárias.",
    "'Underground' é a única palavra na língua inglesa que começa e termina com as letras 'und'",
    "A palavra mais longa da língua inglesa, de acordo com o Oxford English Dictionary, é: pneumonoultramicroscopicsilicovolcanoconiosis..",
    "O nome de lugar mais longo ainda em uso é: Taumatawhakatangihangakoauauotamateaturipukakapikimaungahoronukupokaiakitnatahu, uma colina da Nova Zelândia.",
    "O olho de um avestruz é maior que seu cérebro.",
    "Alfred Hitchcock não tinha umbigo. Foi eliminado quando ele foi suturado após a cirurgia.",
    "Telly Savalas e Louis Armstrong morreram em seus aniversários.",
    "O nome do meio do Pato Donald é Fauntleroy.",
    "O focinho de um leão é como uma impressão digital - não há dois leões com o mesmo padrão de bigodes.",
    "Steely Dan recebeu seu nome de um dispositivo sexual retratado no livro 'The Naked Lunch'.",
    "O preservativo da marca Ramsés leva o nome do grande faraó Ramsés II, que foi pai de mais de 160 filhos.",
    "Há uma palavra de sete letras na língua inglesa que contém dez palavras sem reorganizar nenhuma de suas letras, 'therein': the, there, he, in, rein, her, here, ere, therein, here.",
    "Um peixe-dourado tem uma memória com duração de três segundos. ",
    "Os cranberries são classificados quanto ao amadurecimento, saltando-os; um cranberry totalmente amadurecido pode ser driblado como uma bola de basquete.",
    "A mariposa cigana macho pode 'cheirar' a mariposa cigana virgem a 2,9 quilômetros de distância.",
    "As letras KGB significam Komitet Gosudarstvennoy Bezopasnosti.",
    "A palavra 'dexter' cujo significado se refere à mão direita é digitada apenas com a mão esquerda.",
    "Para 'testemunhar' foi baseado em homens na corte romana jurando uma declaração feita jurando em seus testículos.",
    "Faceto e abstêmio contêm todas as vogais na ordem correta, assim como arsênio, que significa 'contendo arsênico'. ",
    "A palavra 'xeque-mate' no xadrez vem da frase persa 'Shah Mat', que significa 'o rei está morto.'",
    "O primeiro episódio de 'Joanie Loves Chachi' foi o programa americano de maior audiência na história da televisão coreana, um país onde 'Chachi' se traduz em 'pênis'.",
    "Os elásticos duram mais quando refrigerados.",
    "O hino nacional da Grécia tem 158 versos. Ninguém na Grécia memorizou todos os 158 versos.",
    "Dois terços da berinjela do mundo são cultivados em Nova Jersey.",
    "A lula gigante tem os maiores olhos do mundo.", "As girafas não têm cordas vocais.",
    "As pupilas dos olhos de uma cabra são quadradas.", "Van Gogh vendeu apenas uma pintura quando estava vivo.",
    "Um slinky padrão mede 87 pés quando esticado.",
    "O maior consumo per capita de gelatina nos EUA é Des Moines.",
    "Se um galo não consegue esticar totalmente o pescoço, ele não pode cantar.",
    "Sempre havia 56 cachos no cabelo de Shirley Temple.",
    "Os olhos de um burro estão posicionados de forma que ele possa ver todas as quatro patas o tempo todo.",
    "Molho Worcestershire em essencialmente um ketchup de anchova.",
    "Rhode Island é o único estado em que o lançamento do martelo é um esporte legal do ensino médio.",
    "A vida útil média de um cílio é de cinco meses.", "Uma aranha tem sangue transparente.",
    "Cada acre de plantações americanas colhidas contém 100 libras de insetos.",
    "Príncipe Charles é um ávido colecionador de assentos sanitários.",
    "O nome de rua mais comum nos EUA é Second Street.",
    "Teerã é a cidade mais cara do mundo.",
    "As gotas de suor desenhadas nas histórias em quadrinhos são chamadas de pleuts.",
    "Os bebês têm maior probabilidade de nascer às terças-feiras.",
    "O HyperMart fora de Garland Texas tem 58 caixas.",
    "A lista telefônica de Minneapolis tem 21 páginas de Andersons.",
    "Na década de 1980, as enxaquecas americanas aumentaram 60%",
    "A Polônia é a 'capital mundial dos carros roubados'.",
    "Jefferson inventou o elevador, o sistema monetário e a escada dobrável do sótão.",
    "O S em Harry S. Truman não representava nada.", "Na Miconésia, as moedas têm 3,6 metros de diâmetro.",
    "Um cavalo pode olhar para a frente com um olho e para trás com o outro.",
    "Shakespeare é citado 33.150 vezes no dicionário Oxford English.",
    "A palavra Pensilvânia está escrita incorretamente no Sino da Liberdade.",
    "O superastro da NBA Michael Jordan foi originalmente cortado do time de basquete da escola.",
    "Você passa 7 anos da sua vida no banheiro.",
    "Uma família de 26 pessoas poderia ir ao cinema na Cidade do México pelo preço de uma em Tóquio.",
    "10.000 vacas holandesas passam pelo aeroporto de Amsterdã a cada ano.",
    "Aproximadamente a cada sete minutos de cada dia, alguém em uma aula de aeróbica distende o tendão.",
    "Senhas simplistas contribuem para mais de 80% de todas as invasões de senha de computador.",
    "As 3 principais pesquisas relacionadas à saúde na Internet são (nesta ordem): Depressão, Alergias e Câncer.",
    "Os dentistas recomendam que a escova de dentes seja mantida a pelo menos 2 metros de distância do vaso sanitário para evitar partículas suspensas no ar resultantes da descarga.",
    "A maioria das partículas de poeira em sua casa é feita de pele morta.",
    "Vênus é o único planeta que gira no sentido horário.",
    "Os carvalhos não produzem bolotas até os cinquenta anos de idade ou mais.",
    "O primeiro proprietário da empresa Marlboro morreu de câncer de pulmão.",
    "Todos os presidentes dos Estados Unidos já usaram óculos; alguns simplesmente não gostaram de ser vistos usando-os em público.",
    "Os repelentes de mosquitos não repelem. Eles escondem você. O spray bloqueia os sensores do mosquito para que eles não saibam que você está lá.",
    "Walt Disney tinha medo de ratos.",
    "O site com maior número de visitantes mulheres entre 35 e 44 anos: Alka-Seltzer.com",
    "O rei de copas é o único rei sem bigode.", "Pérolas derretem em vinagre.",
    "São necessárias 3.000 vacas para abastecer a NFL com couro suficiente para um ano de fornecimento de bolas de futebol.",
    "Trinta e cinco por cento das pessoas que usam anúncios pessoais para namoro já são casadas.",
    "As 3 marcas mais valiosas do mundo são Marlboro, Coca-Cola e Budweiser (nessa ordem).",
    "Os humanos são os únicos primatas que não têm pigmento nas palmas das mãos.",
    "Meses que começam em um domingo sempre terão uma 'sexta-feira 13'.",
    "As impressões digitais dos coalas são virtualmente indistinguíveis das dos humanos, tanto que podem ser facilmente confundidas na cena do crime.",
    "A máscara usada por Michael Myers no 'Halloween' original era na verdade uma máscara do Capitão Kirk pintada de branco.",
    "Os únicos dois dias do ano em que não há jogos de esportes profissionais - MLB, NBA, NHL ou NFL - são o dia anterior e o dia seguinte ao jogo All-Star da Major League.",
    "Apenas uma pessoa em dois bilhões viverá até os 116 anos ou mais.",
    "Quando a Academia Francesa estava preparando seu primeiro dicionário, ela definiu 'caranguejo' como, 'Um pequeno peixe vermelho, que anda para trás'. Essa definição foi enviada com várias outras ao naturalista Cuvier para sua aprovação. O cientista respondeu: 'Sua definição, senhores, seria perfeita, apenas com três exceções. O caranguejo não é um peixe, não é vermelho e não anda para trás.'",
    "O primeiro paciente do Dr. Jack Kevorkian tem a doença de Alzheimer.",
    "O escritor de ficção/terror Stephen King dorme com uma luz próxima acesa para acalmar seu medo do escuro.",
    "É possível levar uma vaca para cima, mas não para baixo.",
    "Foi descoberto em uma missão espacial que um sapo pode vomitar. O sapo vomita primeiro o estômago, então o estômago fica pendurado para fora da boca. Em seguida, o sapo usa os antebraços para desenterrar todo o conteúdo do estômago e depois engole o estômago de volta para baixo.",
    "A primeira música tocada na MTV foi 'Video Killed The Radio Star' dos Buggles.",
    "William Marston projetou uma das primeiras formas do polígrafo no início de 1900. Mais tarde, ele criou a história em quadrinhos Mulher Maravilha, uma história sobre uma princesa amazona deslocada que força qualquer pessoa presa em seu laço mágico a dizer a verdade",
    "Os americanos viajam 1.144.721.000 milhas de avião todos os dias",
    "Nos Estados Unidos, você disca '911'. Em Estocolmo, na Suécia, você disca 90000",
    "38% dos homens americanos dizem que amam seus carros mais do que as mulheres",
    "Os militares dos EUA operam 234 campos de golfe", "100% dos ganhadores da loteria ganham peso",
    "Coletes à prova de balas, escadas de incêndio, limpadores de para-brisa e impressoras a laser foram todos inventados por mulheres",
    "Um gato tem 32 músculos em cada orelha.", "O grasnado de um pato não faz eco, e ninguém sabe por quê.",
    "Urina de gato brilha sob luz negra.", "Em cada episódio de Seinfeld há um Superman em algum lugar.",
    "Lorne Greene teve um de seus mamilos arrancado por um crocodilo enquanto era o anfitrião do 'Reino Selvagem de Lorne Greene.'",
    "Pamela Anderson Lee é o bebê do centenário do Canadá, sendo o primeiro bebê nascido no centenário da independência do Canadá.",
    "Pinóquio é italiano para 'cabeça de pinheiro.'",
    "Quando os gambás estão brincando de 'gambá', eles não estão 'brincando'. Eles realmente desmaiam de puro terror.",
    "Quem é aquele tocando piano no tema 'Mad About You'? O próprio Paul Reiser.",
    "Winston Churchill nasceu em um banheiro feminino durante uma dança.", "A maioria dos batons contém escamas de peixe!",
    "Os quadrinhos do Pato Donald foram banidos da Finlândia porque ele não usa calças!",
    "Existem mais de 10 milhões de tijolos no Empire State Building!",
    "Os camelos têm três pálpebras para se protegerem da areia soprada!",
    "A colocação dos olhos de um burro em suas cabeças permite que ele veja todas as quatro patas o tempo todo!",
    "O americano/canadense médio come cerca de 11,9 quilos de cereais por ano!",
    "Mais de 1.000 pássaros morrem por ano ao bater em janelas!",
    "O estado da Flórida é maior que a Inglaterra!", "Golfinhos dormem com um olho aberto!",
    "Na Casa Branca, há 13.092 facas, garfos e colheres!",
    "A reciclagem de uma jarra de vidro economiza energia suficiente para assistir TV por 3 horas!",
    "As corujas são uma das únicas aves que conseguem enxergar a cor azul!",
    "As abelhas têm um tipo de pelo nos olhos!", "Uma água-viva é 95% água!",
    "Em Bangladesh, crianças de até 15 anos podem ser presas por trapacear nas provas finais!",
    "O inseto gafanhoto ouve através de buracos nas patas traseiras!",
    "Q é a única letra do alfabeto que não aparece no nome de nenhum dos Estados Unidos!",
    "166.875.000.000 de correspondências são entregues a cada ano nos EUA",
    "Os morcegos sempre viram à esquerda ao sair de uma caverna",
    "O louva-a-deus é o único inseto que consegue virar a cabeça", "O nome do meio do Patolino é 'Dumas'",
    "Na Fantasia da Disney, o nome do Feiticeiro é 'Yensid' (Disney ao contrário.)",
    "Em O Império Contra-Ataca há uma batata escondida no campo de asteroides",
    "Walt Disney detém o recorde mundial de mais prêmios da Academia ganhos por uma pessoa, ele ganhou vinte estatuetas e outras doze placas e certificados",
    "O carro de James Bond tinha três placas diferentes em Goldfinger",
    "O Canadá representa 6,67 por cento da área terrestre da Terra",
    "Dakota do Sul é o único estado dos EUA que não compartilha letras com o nome de sua capital",
    "A KGB está sediada na Praça Felix Dzerzhinsky nº 2, Moscou",
    "A cidade do Vaticano registou 0 nascimentos em 1983", "Espanha lidera o mundo na produção de cortiça",
    "Há 1.792 degraus na Torre Eiffel",
    "São 269 degraus até o topo da Torre Inclinada de Pisa",
    "Leonardo da Vinci podia escrever com uma mão enquanto desenhava com a outra",
    "Os elásticos duram mais quando refrigerados.", "O amendoim é um dos ingredientes da dinamite.",
    "O hino nacional da Grécia tem 158 versos. Ninguém na Grécia memorizou todos os 158 versos.",
    "Existem 293 maneiras de fazer troco por um dólar.",
    "A mão esquerda da secretária média faz 56% da digitação.",
    "Um tubarão é o único peixe que pode piscar com os dois olhos.",
    "Existem mais galinhas do que pessoas no mundo (pelo menos antes daquela coisa da gripe aviária).",
    "Dois terços da berinjela do mundo são cultivados em Nova Jersey.",
    "A palavra de uma sílaba mais longa na língua inglesa é 'screeched.'",
    "Todos os relógios no filme Pulp Fiction estão parados em 4:20.",
    "Nenhuma palavra na língua inglesa rima com mês, laranja, prata ou roxo.",
    "'Dreamt' é a única palavra em inglês que termina com as letras 'mt'.",
    "Todos os 50 estados estão listados na parte superior do Lincoln Memorial no verso da nota de US$ 5.",
    "As amêndoas são membros da família dos pêssegos.",
    "Winston Churchill nasceu em um banheiro feminino durante uma dança.",
    "Maine é o único estado cujo nome tem apenas uma sílaba.",
    "Existem apenas quatro palavras na língua inglesa que terminam em 'dous': tremendo, horrendo, estupendo e perigoso.",
    "O nome completo de Los Angeles é 'El Pueblo de Nuestra Senora la Reina de los Angeles de Porciuncula'. E pode ser abreviado para 3,63% de seu tamanho, 'L.A.'",
    "Um gato tem 32 músculos em cada orelha.", "O olho de um avestruz é maior que o cérebro.",
    "Tigres têm pele listrada, não apenas pelo listrado.",
    "Na maioria dos anúncios, incluindo jornais, a hora exibida em um relógio é 10:10.",
    "O cartão de visita de Al Capone dizia que ele era um negociante de móveis usados.",
    "A única pessoa real a ser uma cabeça de Pez foi Betsy Ross.",
    "Quando o University of Nebraska Cornhuskers joga futebol em casa, o estádio se torna a terceira maior cidade do estado.",
    "Os personagens Bert e Ernie na Vila Sésamo receberam o nome de Bert, o policial, e Ernie, o motorista de táxi em 'Its A Wonderful Life', de Frank Capra",
    "Uma libélula tem uma vida útil de 24 horas.", "Um peixinho dourado tem uma memória de três segundos.",
    "Um peixinho dourado tem uma memória de três segundos.", "Uma moeda de dez centavos tem 118 arestas ao redor da borda.",
    "Em uma nota de um dólar americano, há uma coruja no canto superior esquerdo do '1' envolto no 'escudo' e uma aranha escondida no canto superior direito frontal.",
    "É impossível espirrar com os olhos abertos.", "A lula gigante tem os maiores olhos do mundo.",
    "Quem é aquele tocando piano no tema 'Mad About You'? O próprio Paul Reiser.",
    "A mariposa cigana macho pode 'cheirar' a mariposa cigana virgem a 2,9 quilômetros de distância (truque muito bom).",
    "Na Inglaterra, o presidente da Câmara não tem permissão para falar.",
    "O nome de Oz no 'Mágico de Oz' foi inventado quando o criador, Frank Baum, olhou para seu arquivo e viu A-N e O-Z, daí 'Oz'",
    "O micro-ondas foi inventado depois que um pesquisador passou por um tubo de radar e uma barra de chocolate derreteu em seu bolso.",
    "Sr. Rogers é um ministro ordenado.", "A primeira namorada de John Lennon se chamava Thelma Pickles.",
    "Uma pessoa normal adormece em sete minutos.",
    "Existem 336 ondulações em uma bola de golfe normal.",
    "'Aeromoças' é a palavra mais longa digitada apenas com a mão esquerda.",
    "A tecla 'libra' em seu teclado (#) é chamada de octotrófico.",
    "O único animal doméstico não mencionado na Bíblia é o gato.",
    "O 'ponto' sobre a letra 'i' é chamado de til.",
    "Sabe-se que as bolas de tênis de mesa saem da raquete a velocidades de até 160 km/h.",
    "Pepsi originalmente continha pepsina, daí o nome.",
    "A história original de 'Tales of 1001 Arabian Nights' começa, 'Aladdin era um garotinho chinês.'",
    "A noz-moscada é extremamente venenosa se injetada por via intravenosa.",
    "O mel é o único alimento natural que é feito sem destruir nenhum tipo de vida. E o leite, você diz? Uma vaca tem que comer grama para produzir leite e a grama está viva.",
    "O alfabeto havaiano tem apenas 12 letras: A, E, I, O, U, H, K, L, M, N, P, W",
    "O mel é o único alimento que não estraga.",
    "E uma única colher de chá de mel representa o trabalho da vida de 12 abelhas.",
    "Flamingos só podem comer com a cabeça virada para baixo.",
    "O isqueiro foi inventado dez anos antes da partida.",
    "É fisicamente impossível para um porco olhar para o céu.",
    "O primeiro nome de domínio da Internet a ser registrado é Symbolics.com em 15 de março de 1985.",
    "O ser humano nasce com 350 ossos no corpo, mas ao atingir a idade adulta, temos apenas 260.",
    "Existem 150 versos no hino nacional grego, o que o torna o hino nacional mais longo do mundo.",
    "Isso é impossível de fazer cócegas em si mesmo.", "Um lápis típico pode desenhar uma linha de 35 milhas de comprimento.",
    "Os astronautas ficam mais altos no espaço devido à falta de gravidade.",
    "A área total da superfície dos pulmões humanos é de 750 pés quadrados. Isso é aproximadamente a mesma área do lado de uma quadra de tênis.",
    "Os mosquitos contribuíram para mais mortes do que qualquer animal na Terra.",
    "Um polvo tem 3 corações, 9 cérebros e sangue azul.",
    "O pelo de um urso polar na verdade não é branco, mas claro. Eles parecem brancos porque refletem a luz.",
    "Um camaleão pode mover seus olhos em duas direções diferentes ao mesmo tempo.",
    "O soro de leite coalhado não contém manteiga e tem baixo teor de gordura.",
    "Uma girafa pode ficar mais tempo sem água do que um camelo.",
    "A Austrália tem a maior população de camelos do mundo.", "Os caracóis podem dormir até 3 anos.",
    "Os gases metano produzidos por produtos de vaca são tão poluentes quanto os carros.",
    "A maior parte do duto em sua casa é feita de sua própria pele morta.",
    "A maioria dos batons contém escamas de peixe.", "A maioria dos sorvetes contém pele de porco (gelatina).",
    "A ilha filipina de Luzon contém um lago que contém uma ilha que contém um lago que contém outra ilha.",
    "A área da baía de Hudson, no Canadá, tinha menos gravidade do que o resto do mundo e os cientistas não sabem por quê.",
    "Apenas um a dois por cento de toda a população mundial são ruivas naturais.",
    "A caligrafia desleixada faz médicos matarem mais de 7.000 pessoas e ferir mais de 1,5 milhão de pessoas anualmente devido ao uso de medicamentos errados.",
    "Colocar açúcar em uma ferida ou corte reduzirá muito a dor e encurtará o processo de cicatrização.",
    "Diamantes reais não aparecem em raios-X.",
    "Devido à extrema pressão e condições climáticas, literalmente chove diamantes em Netuno e Urano.",
    "Existem 7 tipos diferentes de gêmeos: idênticos, fraternos, semi-idênticos, gêmeos espelhados, gêmeos com cromossomos mistos, superfecundação e superfetação.",
    "Antes do século 17, as cenouras eram realmente roxas. Elas não adquiriam a cor laranja até que a mutação ocupou.",
    "Se o sol fosse reduzido ao tamanho de um glóbulo branco, a Via Láctea seria igual ao tamanho dos Estados Unidos.",
    "Uma síndrome de pedantismo gramatical é uma forma de TOC em que os sofredores sentem a necessidade de corrigir todos os erros gramaticais que veem.",
    "Escorpiões podem prender a respiração debaixo d'água por até 6 dias.",
    "Em gravidade zero, a chama de uma vela é redonda e azul.",
    "Apenas 8 por cento do dinheiro do mundo existe em forma física, o resto está em computadores.",
    "Os corvos são capazes de reconhecer rostos humanos e até mesmo guardar rancor daqueles de quem não gostam.",
    "Seu celular carrega até dez vezes mais bactérias do que um assento de vaso sanitário.",
    "Humanos e bananas compartilham cerca de 50% do mesmo DNA.",
    "Humanos têm menos cromossomos que uma batata.",
    "Um farmacêutico americano chamado John Pemberton inventou a Coca-Cola, que a anuncia como um tônico para os nervos para curar dores de cabeça e fadiga.",
    "Estatisticamente, é mais provável que você morra no caminho para comprar um bilhete de loteria do que ganhe na loteria em si.",
    "A palavra xeque-mate vem do árabe e significa 'o rei está morto'",
    "A água quente se transforma em gelo mais rapidamente do que a água fria. Isso é conhecido como efeito Mpemba.",
    "A missão Apollo 7 foi o primeiro 'sorvete de astronauta' voado no espaço. No entanto, era tão impopular entre os astronautas e foi retirado do menu após apenas uma viagem ao espaço.",
    "Os astronautas da Apollo 8 foram os primeiros a celebrar o Natal no espaço.",
    "IV é a designação do numeral romano para 4 em todos os lugares. No entanto, no mostrador do relógio, 4 é exibido como 'IIII'.",
    "O Apple Macintosh tinha as assinaturas de sua equipe de design gravadas dentro de seu estojo.",
    "O Japão tem o maior número de máquinas de venda per capita, impressionantes 1:23.",
    "Um estudo da Universidade de Chicago em 1915 concluiu que a cor mais fácil de identificar à distância é a cor amarela. É por isso que a cor mais popular para os táxis é o amarelo.",
    "A polícia japonesa declara os assassinatos que não podem resolver como suicídios, a fim de salvar rostos e manter a taxa de criminalidade artificialmente baixa.",
    "Os menores sapos venenosos com apenas 10 milímetros (0,393701 polegada) de comprimento.",
    "Peidar ajuda a reduzir a pressão arterial e é bom para a saúde em geral.",
    "Em 1994, a Força Aérea dos EUA pesquisou a criação de uma bomba gay (são nomes informais para arma química teórica não letal), que é uma bomba não letal contendo feromônios sexuais humanos muito fortes que fariam as forças inimigas atraídas umas pelas outras. .",
    "Existem cerca de 1.584 pessoas nos Estados Unidos com o nome 'Sete'.",
    "A forma clássica de coração que todos conhecemos era para ser dois corações fundidos.",
    "A água que bebemos é mais antiga que o sol. O sol tem 4,6 bilhões de anos.",
    "A água em nosso planeta é muito antiga. A água que temos agora é a mesma que existia centenas de milhões de anos atrás. Da próxima vez que você beber um copo de água, poderá estar prestes a beber um gole de xixi de dinossauro.",
    "Enquanto isso, cerca de 40% dos americanos acham que humanos e dinossauros existiram ao mesmo tempo.",
    "Ninguém sabe quem nomeou nosso planeta 'Terra'.",
    "Michael Nicholson de Michigan. Ele tem um diploma de bacharel, dois diplomas de associado, 22 mestrados, três diplomas de especialização e um doutorado, tornando-o a pessoa mais credenciada da história.",
    "Praticar uma matança em sua cabeça o tornará melhor nisso, mas apenas se você já for bom nisso.",
    "Se dois gêmeos idênticos tiverem filhos com outro par de gêmeos idênticos, então seus filhos serão geneticamente irmãos completos.",
    "Matar um panda na China é um crime grave. É punível com a morte.",
    "4 de dezembro é o Dia Nacional do Biscoito!",
    "A barba pode retardar o processo de envelhecimento ao impedir que a água saia da pele, mantendo-a hidratada.",
    "Uma pesquisa descobriu que 33% dos homens e 43% das mulheres afirmaram que se apaixonaram por alguém que inicialmente não acharam atraente.",
    "A maioria das pessoas sonha em cores, mas aqueles que crescem assistindo televisão em preto e branco são mais propensos a sonhar em preto e branco.",
    "Misturar suas bebidas com refrigerante diet pode deixá-lo bêbado cerca de 18% mais rápido do que o refrigerante comum. Hummm…",
    "O número de moléculas de H2O em 10 gotas de água é aproximadamente igual à quantidade total de estrelas no universo.",
    "Os polvos têm sangue à base de cobre em vez de sangue à base de ferro, e é por isso que seu sangue é azul em vez de vermelho.",
    "Além disso, eles têm três corações e nove cérebros",
    "Os hormônios responsáveis ​​pelo seu crescimento só são produzidos quando você dorme.",
    "Você toca seu rosto em média uma vez a cada três minutos. E você tocou seu rosto corretamente depois de lê-lo.",
    "Pessoas que dormem menos de seis horas por noite têm 4,2 vezes mais chances de pegar um resfriado em comparação com aquelas que dormem mais de sete horas.",
    "Os cães podem fazer cerca de 100 expressões faciais diferentes.",
    "A Islândia não tem exército, pois é frequentemente reconhecida como o país mais pacífico do mundo.",
    "Shigeru Miyamoto – criador de Super Mario Bros. e Donkey Kong – não tem permissão para ir de bicicleta para o trabalho porque sua segurança é muito importante para a Nintendo.",
    "A cada ano, as mulheres perdem aproximadamente 1,73 bilhão de grampos de cabelo.",
    "Os golfinhos dão 'nomes' uns aos outros – sons específicos que eles usam para chamar amigos e familiares.",
    "Bebês chimpanzés gostam de brincar com bonecas – Eles fazem bonecas com paus e pedras para eles mesmos.",
    "Os esquilos plantam milhares de árvores todos os anos, simplesmente esquecendo onde colocaram suas bolotas.",
    "Os coalas podem dormir até 20 horas por dia.",
    "A mulher média passará um ano inteiro de sua vida tentando decidir o que vestir.",
    "A mulher média possui oito vezes mais maquiagem do que ela realmente usa.",
    "Arcos-íris que aparecem à noite são chamados de 'arcos-íris'",
    "Há 100 milhões de anos, os crocodilos tinham pernas longas e podiam galopar atrás de suas presas.",
    "A verdadeira escola Top Gun dá uma multa de $ 5 para qualquer membro da equipe que cite o filme.",
    "Na vila Biertan (localizada na Transilvânia, Romênia), a igreja tinha uma sala de reconciliação de divórcio. Casais que queriam se divorciar tinham que viver em um quarto por duas semanas com uma cama pequena, uma cadeira, uma mesa, um prato e uma colher. Em 300 anos, eles só tiveram um divórcio.")

   export default { useless_facts: useless_facts};